spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useSSL=false&serverTimezone=UTC
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        cluster-name: BJ
#        namespace: 68dc03c0-048d-48c4-81e3-b7d1b34556e5
#        metadata:
#          version: v1
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          # 用来指定topic,跟生产端一样
#          destination: stream-test-topic
          destination: add-bonus
          # 如果是RocketMQ,一定要设置，其他的mq可以留空
          group: binder-group
#        my-input:
#          destination: stream-my-topic
#          # 如果是RocketMQ,一定要设置，其他的mq可以留空
#          group: my-group

  application:
    name: user-center
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      #抽样率：默认是0.1，表示90%的数据都会丢弃，这里我们测试方便用了1.0
      probability: 1.0
server:
  port: 8002
#rocketmq:
#  name-server: 127.0.0.1:9876

jwt:
  secret: aaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrsssttt
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
logging:
  level:
    org.springframework.cloud.sleuth: debug


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always