spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useSSL=false&serverTimezone=UTC
    hikari:
      username: root
      password: 1323!Q@#EMSD%$^
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: user-center
server:
  port: 8008
