spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useSSL=false&serverTimezone=UTC
    hikari:
      username: root
      password: 1323!Q@#EMSD%$^
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
        namespace: 68dc03c0-048d-48c4-81e3-b7d1b34556e5
        metadata:
          version: v1

  application:
    name: user-center
server:
  port: 8002
